version: "3.5"
services:
  twap:
    image: tulip-protocol/jup-twap:latest
    command: lib/index.js twap --from USDC --to TULIP --amount 1 --interval 1m
    security_opt:
      - apparmor:docker-default
      - seccomp=./seccomp_default.json
      - no-new-privileges
    environment:
      RPC_URL: ..
      WALLET_PK: ..